from dataclasses import dataclass

from chess.contracts.board_state_view import BoardStateView
from chess.models.move import Move
from chess.models.piece_type import PieceType
from chess.models.square import Square
from chess.models.vector import Vector
from chess.movement.direction_sets import ALL_EIGHT_DIRECTIONS
from chess.movement.step_scanner import StepScanner
from chess.pieces.base_piece import BasePiece

KING_OFFSETS: tuple[Vector, ...] = tuple(direction.vector for direction in ALL_EIGHT_DIRECTIONS)


@dataclass(frozen=True, slots=True)
class King(BasePiece):
    """
    One step in any direction.

    Castling is generated by the rules layer, because its availability depends on
    which squares the enemy attacks.
    """

    @property
    def piece_type(self) -> PieceType:
        return PieceType.KING

    def pseudo_legal_moves(self, state: BoardStateView) -> tuple[Move, ...]:
        return StepScanner.moves_to_offsets(
            state=state,
            origin=self.square,
            color=self.color,
            piece_type=self.piece_type,
            offsets=KING_OFFSETS,
        )

    def attacked_squares(self, state: BoardStateView) -> frozenset[Square]:
        return StepScanner.attacked_squares_at_offsets(origin=self.square, offsets=KING_OFFSETS)
